// Code generated by "stringer -type BloodType blood_type.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[B-1]
	_ = x[O-2]
	_ = x[AB-3]
}

const _BloodType_name = "ABOAB"

var _BloodType_index = [...]uint8{0, 1, 2, 3, 5}

func (i BloodType) String() string {
	if i < 0 || i >= BloodType(len(_BloodType_index)-1) {
		return "BloodType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BloodType_name[_BloodType_index[i]:_BloodType_index[i+1]]
}
